import os
import logging
from typing import Dict, List, Any
# Standard import for the official new google-genai SDK
try:
    from google import genai
    from google.genai import types
    HAS_GENAI = True
except ImportError:
    HAS_GENAI = False

logger = logging.getLogger("app.services.gemini")

class GeminiService:
    def __init__(self):
        self.api_key = os.environ.get("GEMINI_API_KEY", "")
        self.client = None
        
        if HAS_GENAI and self.api_key:
            try:
                # Initialize new genai client
                self.client = genai.Client(api_key=self.api_key)
                logger.info("Gemini Service initialized with live API client.")
            except Exception as e:
                logger.error(f"Failed to initialize Gemini Client: {e}")
        else:
            logger.info("Gemini Service initialized in MOCK mode (No GEMINI_API_KEY found or google-genai not loaded).")

    def generate_plan(self, requirements: str, target_os: str) -> Dict[str, Any]:
        """
        Planner Agent: Generates a list of steps required to install the software based on input prompt.
        """
        if self.client:
            try:
                prompt = (
                    f"Create an installation plan for: '{requirements}' on target OS: '{target_os}'.\n"
                    f"Return a JSON list of steps. Each step should contain: "
                    f"a 'step_number' (int), 'title' (string), and 'description' (string)."
                )
                response = self.client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        system_instruction="You are an expert systems engineer and software installation planner. Always output valid JSON lists."
                    )
                )
                import json
                return json.loads(response.text)
            except Exception as e:
                logger.warning(f"Error calling live Gemini for generate_plan: {e}. Falling back to mock.")
        
        # Fallback Mock Plan
        return {
            "steps": [
                {
                    "step_number": 1,
                    "title": "System Update and Dependency Installation",
                    "description": f"Verify system packages are up-to-date and install baseline tools required for {requirements} on {target_os}."
                },
                {
                    "step_number": 2,
                    "title": "Install Core Components",
                    "description": f"Download, extract, and configure target software binaries for {requirements}."
                },
                {
                    "step_number": 3,
                    "title": "Service and Daemon Configuration",
                    "description": f"Set up configuration files, service bindings, environment variables, and verify service autostart."
                }
            ]
        }

    def generate_script(self, requirement: str, target_os: str, step_title: str) -> Dict[str, str]:
        """
        Generator Agent: Generates executable script content for the current step.
        """
        if self.client:
            try:
                prompt = (
                    f"Generate a single, complete script to execute the step '{step_title}' for the installation requirement: '{requirement}' on target OS '{target_os}'.\n"
                    f"Return a JSON object with keys: 'filename' (string), 'language' (string, e.g. bash, powershell), 'content' (string, executable code), 'description' (string)."
                )
                response = self.client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        system_instruction="You are a system administrator script generator. Provide executable, clean, commented scripts."
                    )
                )
                import json
                return json.loads(response.text)
            except Exception as e:
                logger.warning(f"Error calling live Gemini for generate_script: {e}. Falling back to mock.")

        # Fallback Mock Scripts based on target OS
        os_lower = target_os.lower()
        if "win" in os_lower:
            filename = f"install_{step_title.lower().replace(' ', '_')}.ps1"
            language = "powershell"
            content = (
                f"# Powershell Script for: {step_title}\n"
                f"# Automatically generated by InstallGen AI\n\n"
                f"Write-Host 'Starting step: {step_title} for {requirement}' -ForegroundColor Green\n"
                f"try {{\n"
                f"    # Check elevated rights\n"
                f"    $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)\n"
                f"    if (-not $isAdmin) {{\n"
                f"        Write-Warning 'Elevated administrator rights are recommended.'\n"
                f"    }}\n"
                f"    # Run dummy script setup steps\n"
                f"    Write-Host 'Updating environment paths...'\n"
                f"    Start-Sleep -Seconds 1\n"
                f"    Write-Host '{step_title} successfully run.' -ForegroundColor Green\n"
                f"}} catch {{\n"
                f"    Write-Error $_.Exception.Message\n"
                f"    exit 1\n"
                f"}}\n"
            )
        else:
            filename = f"install_{step_title.lower().replace(' ', '_')}.sh"
            language = "bash"
            content = (
                f"#!/bin/bash\n"
                f"# Bash script for: {step_title}\n"
                f"# Automatically generated by InstallGen AI\n\n"
                f"set -e\n"
                f"echo -e '\\033[0;32m[+] Starting step: {step_title} for {requirement}\\033[0m'\n\n"
                f"# Verify if sudo\n"
                f"if [ \"$EUID\" -ne 0 ]; then\n"
                f"  echo 'Warning: Running without sudo permissions.'\n"
                f"fi\n\n"
                f"echo 'Setting up environment directories...'\n"
                f"sleep 1\n"
                f"echo -e '\\033[0;32m[+] Completed step: {step_title} successfully.\\033[0m'\n"
            )

        return {
            "filename": filename,
            "language": language,
            "content": content,
            "description": f"Automated script file mapping to installation phase: {step_title}."
        }

    def audit_script(self, filename: str, script_content: str, target_os: str) -> Dict[str, Any]:
        """
        Auditor Agent: Scans script content for security vulnerabilities, commands injection, hardcoded secrets.
        """
        if self.client:
            try:
                prompt = (
                    f"Audit the following installation script for file '{filename}' on OS '{target_os}':\n"
                    f"```\n{script_content}\n```\n"
                    f"Return a JSON object containing:\n"
                    f"- 'passed' (boolean)\n"
                    f"- 'score' (int out of 100)\n"
                    f"- 'summary' (string overview)\n"
                    f"- 'issues' (JSON list of strings detailing findings or security recommendations)"
                )
                response = self.client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        system_instruction="You are a security auditor specialized in infrastructure and devops scripts. Scan for hardcoded credentials, remote execution, unvalidated inputs, and privilege escalation vulnerabilities."
                    )
                )
                import json
                return json.loads(response.text)
            except Exception as e:
                logger.warning(f"Error calling live Gemini for audit_script: {e}. Falling back to mock.")

        # Fallback Mock Audit
        return {
            "passed": True,
            "score": 95,
            "summary": f"Security audit passed for script {filename}. Safe commands structure found.",
            "issues": [
                "RECOMMENDATION: Avoid running script blindly using curl | sh, execute downloaded script locally.",
                "NOTE: Script does not contain any hardcoded passwords or active secrets."
            ]
        }

    def verify_deployment(self, requirement: str, target_os: str, scripts: List[Dict[str, str]]) -> Dict[str, Any]:
        """
        Verifier Agent: Validates the deployment, checks service endpoints/commands to verify installation success.
        """
        if self.client:
            try:
                script_list_summary = ", ".join([s.get("filename", "") for s in scripts])
                prompt = (
                    f"Generate verification checks for installation request '{requirement}' on target OS '{target_os}'.\n"
                    f"List of scripts generated: {script_list_summary}.\n"
                    f"Return a JSON object with keys:\n"
                    f"- 'passed' (boolean, simulated result)\n"
                    f"- 'score' (int, 0-100)\n"
                    f"- 'summary' (string explanation)\n"
                    f"- 'details' (JSON list of strings containing verification steps and commands to run)"
                )
                response = self.client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        system_instruction="You are a QA automation system verifier. Validate system configuration status and daemon presence."
                    )
                )
                import json
                return json.loads(response.text)
            except Exception as e:
                logger.warning(f"Error calling live Gemini for verify_deployment: {e}. Falling back to mock.")

        # Fallback Mock Verification
        is_win = "win" in target_os.lower()
        checks = [
            f"Run service status commands to verify service bindings." if not is_win else "Get-Service to verify daemon bindings.",
            f"Check system logs in syslog for active errors." if not is_win else "Check Event Viewer Application logs.",
            f"Perform a request to loopback port to check socket connectivity."
        ]
        return {
            "passed": True,
            "score": 100,
            "summary": f"All installation validation checklists passed successfully for {requirement}.",
            "details": checks
        }

    def chat_assistant(self, message: str, history: list) -> str:
        """
        AI Assistant: Chat with systems administrator helper.
        """
        if self.client:
            try:
                # Compile conversation history format for gemini
                prompt = "You are a professional systems administrator and devops assistant for InstallGen AI. Respond to the user request. Keep code blocks clean.\n\n"
                for h in history:
                    role = "User" if h.get("sender") == "user" else "Assistant"
                    prompt += f"{role}: {h.get('text')}\n"
                prompt += f"User: {message}\nAssistant:"
                
                response = self.client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=prompt,
                )
                return response.text
            except Exception as e:
                logger.warning(f"Error calling live Gemini for chat_assistant: {e}. Falling back to mock.")
        
        # Fallback Mock Assistant responses
        msg_lower = message.lower()
        if "nginx" in msg_lower:
            return "To configure Nginx as a reverse proxy, you should update the `/etc/nginx/sites-available/default` file with a `proxy_pass` directive inside the `location /` block. For example:\n\n```nginx\nserver {\n    listen 80;\n    location / {\n        proxy_pass http://localhost:3000;\n    }\n}\n```\nThen restart nginx with `sudo systemctl restart nginx`."
        elif "powershell" in msg_lower or "windows" in msg_lower:
            return "In PowerShell, you can check active service status using `Get-Service` or restart a service with `Restart-Service -Name <name>`. Make sure you run PowerShell as an Administrator to execute installations."
        else:
            return f"Thank you for asking! I'm here as your InstallGen AI DevOps assistant. Regarding '{message}', I recommend setting up an automated pipeline using our Multi-Agent Planner to generate executable scripts, which will run verification checks and audit them for security compliance before deploying."

    def troubleshoot_error(self, error_log: str, script_context: str = "") -> Dict[str, Any]:
        """
        Troubleshooter Agent: Analyzes log errors and scripts to provide suggestions.
        """
        if self.client:
            try:
                prompt = (
                    f"Analyze this installation error log:\n"
                    f"```\n{error_log}\n```\n"
                    f"Script context:\n"
                    f"```\n{script_context}\n```\n"
                    f"Return a JSON object containing:\n"
                    f"- 'root_cause' (string explanation)\n"
                    f"- 'solution' (string suggested fix with steps)\n"
                    f"- 'recovery_script' (string, shell script code to run to fix/cleanup)"
                )
                response = self.client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        system_instruction="You are a systems engineer troubleshooting daemon. Analyze the logs, locate permissions issues, packages missing, or networking faults, and output JSON with root_cause, solution, and recovery_script."
                    )
                )
                import json
                return json.loads(response.text)
            except Exception as e:
                logger.warning(f"Error calling live Gemini for troubleshoot_error: {e}. Falling back to mock.")

        # Fallback Mock Troubleshooting
        return {
            "root_cause": "Failed to bind to port 80. The port is already in use by another service (possibly Apache or another Nginx worker instance).",
            "solution": "1. Identify the process using port 80 using netstat or lsof.\n2. Stop the conflicting service, or edit Nginx configuration to listen on another port (e.g. 8080).\n3. Reload or restart the daemon.",
            "recovery_script": "# Run this script to free port 80 or inspect processes\n\n# Find process using port 80\nif command -v lsof >/dev/null; then\n  sudo lsof -i :80\nelse\n  sudo netstat -tulpn | grep :80\nfi\n\n# Suggestion to stop apache2 if running\nif systemctl is-active --quiet apache2; then\n  echo \"Stopping conflicting apache2 service...\"\n  sudo systemctl stop apache2\n  sudo systemctl disable apache2\nfi\n"
        }

gemini_service = GeminiService()

